### ISSUE TITLE
precise input for `SynapseSlider+`

### ISSUE THREAD

**Issue by visualizor** [visualizor/GH_Eto#24]
double or right click to input precise numbers

**Comment by visualizor** [comment]
need to use check mark and cross to signify ok and cancel buttons

**Comment by TarasKydon** [comment]
can use logic? 
left click mouse outside  of the zone = close  
right click with the mouse in the zone = change Value

key escape = close  
key enter = change Value

**Comment by visualizor** [comment]
showmodal won't let user click outside
use [this](https://stackoverflow.com/questions/4507483/winforms-close-modal-dialog-when-clicking-outside-the-dialog)

**Comment by TarasKydon** [comment]
i tested ... change Value is not captured. not a button not an enter key.
